# Generated by Django 3.2.23 on 2024-02-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(default='x@x.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='order_number',
            field=models.CharField(default='x', max_length=2555, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_product_id',
            field=models.CharField(default='x', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
    ]
