# Generated by Django 3.2.23 on 2024-03-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='SignupModel',
        ),
    ]
