# Generated by Django 3.2.23 on 2024-02-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='muscle_group',
            field=models.CharField(default='Chest', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='body_part',
            field=models.IntegerField(choices=[(0, 'legs'), (1, 'arms'), (2, 'chest'), (3, 'shoulders'), (4, 'back')], default=0),
        ),
    ]
