# Generated by Django 3.2.23 on 2024-02-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20240219_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='muscle_group',
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='Chest Day', max_length=75),
            preserve_default=False,
        ),
    ]
